[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@ethereum-attestation-service/=node_modules/@ethereum-attestation-service/",
    "hardhat/=node_modules/hardhat/",
]

# Solidity 컴파일러 설정
solc_version = "0.8.30"

# 공격적인 최적화 (크기 최소화)
optimizer = true
optimizer_runs = 1          # 배포 크기 최소화 (가스비는 증가)
via_ir = true
bytecode_hash = "none"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
